/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pricipalPKG;

import integracion_numerica.Regla_del_Trapecio;
import integracion_numerica.Rosemberg;
import integracion_numerica.Simpson_TresOctavos;
import integracion_numerica.Simpson_UnTercio;
import javax.swing.JOptionPane;

/**
 *
 * @author kevin Figueroa
 */
public class Integracion extends javax.swing.JFrame {

    /**
     * Creates new form Integracion
     */
    public Integracion() {
        initComponents();
        this.setLocationRelativeTo(null);
        pnlRosemberg.setVisible(false);

    }
    
    public String getFuncion() {
        int funcion = cmbFuncion.getSelectedIndex() + 1;
        switch (funcion) {
            case 1:
                txtA.setText("");
                txtB.setText("");
                txtA.setText("1");
                txtB.setText("1.4");
                return "sin(x)";
            
            case 2:
                txtA.setText("");
                txtB.setText("");
                txtA.setText("0");
                txtB.setText("1.2");
                return "x*(e^x)";            
            case 3:
                txtA.setText("");
                txtB.setText("");
                txtA.setText("-1");
                txtB.setText("1");
                return "sin(x)*(1/x)";
            case 4:
                txtA.setText("");
                txtB.setText("");
                txtA.setText("2");
                txtB.setText("3");
                return "(x^2)*ln(x)";
            case 5:
                txtA.setText("");
                txtB.setText("");
                txtA.setText("0");
                txtB.setText("3.1415926");
                return "(x^2)*sin(x) ";
            case 6:
                txtA.setText("");
                txtB.setText("");
                txtA.setText("0");
                txtB.setText("3.1415926");
                return "1/((x^2)+1)^(0.5)";
            
            default:
                JOptionPane.showMessageDialog(null, "ERROR");
        }
        
        return "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbFuncion = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        spnr = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        pnlResult = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtB = new javax.swing.JTextField();
        txtA = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtH = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtResp = new javax.swing.JTextField();
        pnlRosemberg = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTextHoja = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));

        jLabel2.setText("1.Regla del Trapecio");

        jLabel3.setText("2.Regla 1/3 de Simpson");

        jLabel4.setText("3.Regla 3/8 de Simpson");

        jLabel5.setText("4.Rosemberg");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(34, 34, 34)
                .addComponent(jLabel5)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 103, -1, -1));

        cmbFuncion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ∫sen(x) dx    Limites: 1 a 1.4", " ∫x (e^x) dx   Limites: 0 a 1.2", " ∫sen(x)/ x dx Limites: -1 a 1", " ∫x²Ln(x) dx    Limites: 2 a 3", " ∫x²sen(x) dx  Limites: 0 a π ", " ∫dx/√ (x²+1)  Limites 0 a π " }));
        getContentPane().add(cmbFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 12, 238, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jButton1.setText("Solución");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 66, -1, -1));

        spnr.setModel(new javax.swing.SpinnerNumberModel(0, 0, 4, 1));
        getContentPane().add(spnr, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 69, 41, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione el Método");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 71, -1, -1));

        pnlResult.setBackground(new java.awt.Color(153, 153, 255));

        jLabel6.setText("Limite Superior:");

        txtB.setEditable(false);

        txtA.setEditable(false);

        jLabel7.setText("Limite Inferior:");

        jLabel8.setText("H=");

        jLabel9.setText("Valor Apróximado:");

        txtResp.setEditable(false);
        txtResp.setText(" ");

        javax.swing.GroupLayout pnlResultLayout = new javax.swing.GroupLayout(pnlResult);
        pnlResult.setLayout(pnlResultLayout);
        pnlResultLayout.setHorizontalGroup(
            pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlResultLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlResultLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlResultLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(4, 4, 4)
                        .addComponent(txtResp, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlResultLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtH, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        pnlResultLayout.setVerticalGroup(
            pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(pnlResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 103, -1, -1));

        pnlRosemberg.setBackground(new java.awt.Color(0, 0, 0));

        JTextHoja.setColumns(20);
        JTextHoja.setRows(5);
        jScrollPane1.setViewportView(JTextHoja);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Rosemberg");

        javax.swing.GroupLayout pnlRosembergLayout = new javax.swing.GroupLayout(pnlRosemberg);
        pnlRosemberg.setLayout(pnlRosembergLayout);
        pnlRosembergLayout.setHorizontalGroup(
            pnlRosembergLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(pnlRosembergLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlRosembergLayout.setVerticalGroup(
            pnlRosembergLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRosembergLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlRosemberg, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 232, 395, 114));

        jButton2.setBackground(new java.awt.Color(0, 204, 51));
        jButton2.setText("<<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/otroFondo.jpg"))); // NOI18N
        jLabel11.setText("           ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pnlRosemberg.setVisible(false);
        String funcion = getFuncion();
        JTextHoja.setText("");
        if (spnr.getValue().equals(1)) {
             int n;
            do{
                  n = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el número de intervalos: "));
            }while(n<=0);
          
            double a = Double.parseDouble(txtA.getText());
            double b = Double.parseDouble(txtB.getText());
            Regla_del_Trapecio rt = new Regla_del_Trapecio(funcion, a, b);
            rt.setN(n);
            txtH.setText(rt.asche() + "");
            if (n == 1) {
                txtResp.setText("" + rt.simple());
            } else {
                txtResp.setText("" + rt.compuesto(rt.relleno(rt.asche()), rt.asche()));
            }
        } else if (spnr.getValue().equals(0)) {
            txtA.setText("");
            txtB.setText("");
            txtH.setText("");
            txtResp.setText("");
            JOptionPane.showMessageDialog(null, "Seleccione un método válido");
            
        } else if (spnr.getValue().equals(2)) { // simpson 1/3
            
             int n;
            do{
                  n = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el número de intervalos: "));
            }while(n<=0);
            double a = Double.parseDouble(txtA.getText());
            double b = Double.parseDouble(txtB.getText());
            
            Simpson_UnTercio sunt = new Simpson_UnTercio(funcion, a, b);
            sunt.setN(n);
            txtH.setText(sunt.asche() + "");
            if (n == 1) {
                txtResp.setText(sunt.simpson_simple(sunt.asche()) + "");
            } else {
                txtResp.setText("" + sunt.simpson_compuesto(sunt.asche(), sunt.sumatoria_uno(sunt.asche()), sunt.sumatoria_dos(sunt.asche())));
            }
        } else if (spnr.getValue().equals(3)) { // simpson 3/8
            JTextHoja.setText("");
             int n;
            do{
                  n = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el número de intervalos: "));
            }while(n<=0);
            double a = Double.parseDouble(txtA.getText());
            double b = Double.parseDouble(txtB.getText());
            
            Simpson_TresOctavos stOcv = new Simpson_TresOctavos(funcion, a, b);
            stOcv.setN(n);
            txtH.setText(stOcv.asche() + "");
            if (n == 1) {
                txtResp.setText("" + stOcv.simpson_simple(stOcv.asche()));
            } else {
                txtResp.setText("" + stOcv.simpson_compuesto(stOcv.asche(), stOcv.sumatoria_uno(stOcv.asche()), stOcv.sumatoria_dos(stOcv.asche()), stOcv.sumatoria_tres(stOcv.asche())));
            }
        } else if (spnr.getValue().equals(4)) { // Rosemberg
            JTextHoja.setText("");
                    pnlRosemberg.setVisible(true);

            int n;
            do{
           n= Integer.parseInt(JOptionPane.showInputDialog("¿Hasta que nivel de Rosemberg desea?: "));
            }while(n<=0);
            double a = Double.parseDouble(txtA.getText());
            double b = Double.parseDouble(txtB.getText());
            
            Rosemberg ros = new Rosemberg(funcion, a, b);
            ros.setNivel(n);
            String cadena = "", eches = "";
            for (int i = 0; i < ros.aches().length; i++) {
                eches = eches + ros.aches()[i] + ",";
            }
            txtH.setText(eches);
            for (int i = 0; i < n + 1; i++) {
                for (int j = 0; j < n + 2; j++) {
                    if (ros.levels(ros.aches())[i][j] != 0.0) {
                        cadena = cadena + (ros.levels(ros.aches())[i][j] + "      ");
                        txtResp.setText("" + ros.levels(ros.aches())[i][j]);
                    }
                }
                cadena = cadena + ("\n");
            }
            JTextHoja.setText("\n" + cadena);
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      Portada p = new Portada();
      p.show();
      this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Integracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Integracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Integracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Integracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Integracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTextHoja;
    private javax.swing.JComboBox<String> cmbFuncion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlResult;
    private javax.swing.JPanel pnlRosemberg;
    private javax.swing.JSpinner spnr;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtH;
    private javax.swing.JTextField txtResp;
    // End of variables declaration//GEN-END:variables
}
